### ISSUE TITLE
Does pgbouncerhero support multiple pgbouncer instances that are being load balanced?

### ISSUE THREAD

**Issue by arianf** [kwent/pgbouncerhero#13]
Does pgbouncerhero support multiple pgbouncer instances that are being load balanced?

It seems from the docs, multiple pgbouncer instances are for staging and production.

Is it possible to see overall results when having 15+ pgbouncer's in a round robin configuration?

**Comment by kwent** [comment]
This is already supported! You can configure multiple PgBouncer instances within a single group in `config/pgbouncerhero.yml`:

```yaml
pgbouncers:
  production:
    pgbouncer-1:
      url: postgres://user:pass@pgbouncer1:6432/pgbouncer
    pgbouncer-2:
      url: postgres://user:pass@pgbouncer2:6432/pgbouncer
    pgbouncer-3:
      url: postgres://user:pass@pgbouncer3:6432/pgbouncer
    # ...as many as you need
```

Each PgBouncer instance gets its own card on the overview page with individual stats (databases, pools, connections). They're grouped under the same heading ("production" in this example).

There's no aggregated/combined view across instances at this point — each is shown individually, which is typically more useful for debugging since you can see which specific instance has issues.
